CREATE TABLE usuario (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  senha_hash VARCHAR(255) NOT NULL,
  nickname VARCHAR(80) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL
);

CREATE TABLE evento (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
  owner_uuid CHAR(36) NOT NULL,
  location VARCHAR(255) NOT NULL,
  type ENUM('FUTSAL', 'SOCIETY') NOT NULL,
  status ENUM('UPCOMING', 'LIVE', 'FINISHED') NOT NULL DEFAULT 'UPCOMING',
  max_players INT NOT NULL,
  invite_code VARCHAR(20) NOT NULL UNIQUE,
  team_size INT NOT NULL,
  timer_duration_sec INT NOT NULL,
  goals_limit INT NOT NULL,
  mode ENUM('TEMPO', 'GOLS', 'AMBOS') NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (owner_uuid) REFERENCES usuario(uuid)
);

CREATE TABLE participante (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
  event_uuid CHAR(36) NOT NULL,
  user_uuid CHAR(36),
  guest_name VARCHAR(120),
  role ENUM('ORGANIZER', 'PLAYER') NOT NULL,
  joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (event_uuid) REFERENCES evento(uuid),
  FOREIGN KEY (user_uuid) REFERENCES usuario(uuid)
);

CREATE TABLE invite (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
  event_uuid CHAR(36) NOT NULL,
  invite_code VARCHAR(20) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (event_uuid) REFERENCES evento(uuid)
);

CREATE TABLE friendship (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
  user_uuid CHAR(36) NOT NULL,
  friend_user_uuid CHAR(36) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY uniq_friendship_pair (user_uuid, friend_user_uuid),
  FOREIGN KEY (user_uuid) REFERENCES usuario(uuid),
  FOREIGN KEY (friend_user_uuid) REFERENCES usuario(uuid)
);

CREATE TABLE match_event (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
  event_uuid CHAR(36) NOT NULL,
  player_uuid CHAR(36) NOT NULL,
  type ENUM('GOAL', 'CARD', 'ASSIST', 'OTHER') NOT NULL,
  team ENUM('A', 'B') NOT NULL,
  match_time_ms BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (event_uuid) REFERENCES evento(uuid),
  FOREIGN KEY (player_uuid) REFERENCES usuario(uuid)
);

CREATE TABLE ranking_global (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
  user_uuid CHAR(36) NOT NULL UNIQUE,
  nickname VARCHAR(80) NOT NULL,
  goals INT NOT NULL DEFAULT 0,
  assists INT NOT NULL DEFAULT 0,
  cards INT NOT NULL DEFAULT 0,
  points INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (user_uuid) REFERENCES usuario(uuid)
);

CREATE TABLE ranking_event (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
  event_uuid CHAR(36) NOT NULL,
  user_uuid CHAR(36) NOT NULL,
  nickname VARCHAR(80) NOT NULL,
  goals INT NOT NULL DEFAULT 0,
  assists INT NOT NULL DEFAULT 0,
  cards INT NOT NULL DEFAULT 0,
  points INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  UNIQUE KEY uniq_ranking_event_user (event_uuid, user_uuid),
  FOREIGN KEY (event_uuid) REFERENCES evento(uuid),
  FOREIGN KEY (user_uuid) REFERENCES usuario(uuid)
);

CREATE TABLE live_state (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL DEFAULT (UUID()) UNIQUE,
  event_uuid CHAR(36) NOT NULL UNIQUE,
  started_at_server_epoch_ms BIGINT NOT NULL DEFAULT 0,
  accumulated_time_ms BIGINT NOT NULL DEFAULT 0,
  status ENUM('IDLE', 'RUNNING', 'PAUSED', 'ENDED') NOT NULL DEFAULT 'IDLE',
  score_a INT NOT NULL DEFAULT 0,
  score_b INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (event_uuid) REFERENCES evento(uuid)
);
